AllCops:
  Include:
    - Rakefile
  NewCops: enable
  SuggestExtensions: false

Style/Documentation:
  Enabled: false

Naming/FileName:
  Exclude:
    - 'lib/omniauth-riskalyze.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
